     (
      {
       'available_subsamplings': {},
       'cell_angles': ( 90, 90, 90, ),
       'class': 'Data_State',
       'file_type': 'spider',
       'grid_id': '',
       'name': 'Iter_50_reconstruction.vol',
       'path': 'File123.vol',
       'rotation': (
         ( 1, 0, 0, ),
         ( 0, 1, 0, ),
         ( 0, 0, 1, ),
        ),
       'symmetries': ( ),
       'version': 6,
       'xyz_origin': None,
       'xyz_step': None,
      },
      [
       {
        'class': 'Volume_State',
        'default_rgba': ( 1, 1, 0.69999999999999996, 1, ),
        'region': (
          ( 0, 0, 0, ),
          ( 127, 127, 127, ),
          [ 1, 1, 1, ],
         ),
        'region_list': {
          'class': 'Region_List_State',
          'current_index': 0,
          'named_regions': [ ],
          'region_list': [
            (
             ( 0, 0, 0, ),
             ( 127, 127, 127, ),
            ),
           ],
          'version': 1,
         },
        'rendering_options': {
          'bt_correction': 0,
          'cap_faces': 1,
          'class': 'Rendering_Options_State',
          'color_mode': 'auto8',
          'dim_transparency': 1,
          'dim_transparent_voxels': 1,
          'flip_normals': 0,
          'limit_voxel_count': 1,
          'line_thickness': 1.0,
          'linear_interpolation': 1,
          'maximum_intensity_projection': 0,
          'mesh_lighting': 1,
          'minimal_texture_memory': 0,
          'one_transparent_layer': 0,
          'outline_box_linewidth': 1.0,
          'outline_box_rgb': ( 1.0, 1.0, 1.0, ),
          'projection_mode': 'auto',
          'show_outline_box': 0,
          'smooth_lines': 0,
          'smoothing_factor': 0.29999999999999999,
          'smoothing_iterations': 2,
          'square_mesh': 1,
          'subdivide_surface': 0,
          'subdivision_levels': 1,
          'surface_smoothing': 0,
          'two_sided_lighting': 1,
          'version': 1,
          'voxel_limit': 2.02,
         },
        'representation': 'surface',
        'session_volume_id': 170109804,
        'solid_brightness_factor': 1.0,
        'solid_colors': [
          ( 1, 1, 0.69999999999999996, 1, ),
          ( 1, 1, 0.69999999999999996, 1, ),
          ( 1, 1, 0.69999999999999996, 1, ),
         ],
        'solid_levels': [
          ( -0.0066389646925032186, 0, ),
          ( 0.04023507630676032, 0.98999999999999999, ),
          ( 0.099981263279914856, 1, ),
         ],
        'solid_model': None,
        'surface_brightness_factor': 1.0,
        'surface_colors': [
          ( surface_colors_r_replace, surface_colors_g_replace, surface_colors_b_replace , 1, ),
         ],
        'surface_levels': [ surface_levels_replace, ],
        'surface_model': {
          'active': True,
          'class': 'Model_State',
          'clip_plane_normal': ( 0.0, 0.0, 0.0, ),
          'clip_plane_origin': ( 0.0, 0.0, 0.0, ),
          'clip_thickness': 5.0,
          'display': True,
          'id': id_123 ,
          'name': 'Iter_50_reconstruction.vol',
          'osl_identifier': '#1',
          'subid': 0,
          'use_clip_plane': False,
          'use_clip_thickness': False,
          'version': 4,
          'xform': {
            'class': 'Xform_State',
            'rotation_angle': 0.0,
            'rotation_axis': ( 0.0, 0.0, 1.0, ),
            'translation': ( X_trans , Y_trans , Z_trans , ),
            'version': 1,
           },
         },
        'transparency_depth': 0.5,
        'transparency_factor': 0.0,
        'version': 6,
       },
      ],
     ),
